# Create the container from MySQL.
FROM mysql:5

# Set the MySQL environment variables.
ENV MYSQL_DATABASE=madziki
ENV MYSQL_ROOT_PASSWORD=madziki
ENV MYSQL_USER=madziki_user
ENV MYSQL_PASSWORD=madziki

# Add the latest MySQL dump file to the container.
#COPY ./scripts/* /docker-entrypoint-initdb.d/
